### ISSUE TITLE
CW2

### ISSUE THREAD

**Issue by GlebPashko** [oleksandrblazhko/ai-216-pashko#14]
1.
Старі
FR1.1	Кориистувач шукає інформацію щодо безпечного харчування
FR1.2	Користувач може внести дані щодо свого харчування, алегрій, хвороб
FR1.3	ПП надає поради щодо безпечного харчування для користувача
Змінені
FR1.1	Користувач шукає інформацію щодо безпечного харчування та отримує перелік рекомендацій
FR1.2	Користувач може внести дані щодо свого харчування, алергій та хвороб, але потребує сплатити за індивідуальні поради
FR1.3	ПП надає загальні поради щодо безпечного харчування для всіх користувачів без індивідуальних консультацій
Тепер FR1.1 не є атомарною, оскільки вона включає в себе інше завдання (надання рекомендацій), FR1.2 не є завершеною, оскільки вона потребує сплати за індивідуальні поради, і FR1.3 не є безкоштовною, оскільки надає загальні поради без можливості отримання індивідуальних консультацій.

2.
Розподілена система:
Мобільний додаток для користувачів вимагає розробки інтерфейсів для взаємодії з веб-сервісом та передачі даних між ними. Це призводить до складнішого процесу розробки та тестування.
Веб-сервіс для обробки даних вимагає надійної синхронізації з мобільним додатком та сервером бази даних, що збільшує технічну складність проекту.
Сервер бази даних потребує високого рівня безпеки та надійності для збереження даних, що впливає на технічну складність.

Спеціальні вимоги до навчання користувачів:
З огляду на різноманітну аудиторію користувачів, важливо надати спеціальні функції для навчання користувачів, такі як покрокові інструкції та навчальні модулі.
Ці функції вимагають додаткових ресурсів для розробки та підтримки, що підвищує технічну складність проекту.
Отже, на основі цих обгрунтувань можна визначити показники технічної складності для проекту "Розподілена система" та "Спеціальні вимоги до навчання користувачів" як високі.

**Comment by oleksandrblazhko** [comment]
3) "безкоштовніcть реалізації" порушується, якщо, наприклад, 
використовуються графічний інтерфейс
У вас не всі завдання виконано правильно.
Оцінка = 3 бали
